package com.example.game.platformer.localization

import com.example.game.platformer.PlayerSkinOption

data class GameStrings(
    val mainTitle: String,
    val mainSubtitle: String,
    val coinsLabel: String,
    val play: String,
    val shop: String,
    val achievements: String,
    val records: String,
    val statistics: String,
    val back: String,
    val levelSelectTitle: String,
    val levelSelectHint: String,
    val timeAttackChip: String,
    val levelWord: String,
    val backToMainMenu: String,
    val timeAttackScreenTitle: String,
    val timeAttackScreenSubtitle: String,
    val backToLevelSelect: String,
    val timeLimitNone: String,
    val recordsTitle: String,
    val recordsSortHint: String,
    val place1: String,
    val place2: String,
    val place3: String,
    val placeSuffix: String,
    val medalGold: String,
    val medalSilver: String,
    val medalBronze: String,
    val achievementsTitle: String,
    val achievementsUnlockedPrefix: String,
    val achievementsAutoSave: String,
    val achievementDone: String,
    val achievementLocked: String,
    val statisticsTitle: String,
    val statisticsSubtitle: String,
    val statWalletCoins: String,
    val statLifetimeDeaths: String,
    val statLifetimeCoins: String,
    val statLevelsCompleted: String,
    val statPlayTime: String,
    val statUnlockedLevels: String,
    val statAchievements: String,
    val statPaidSkins: String,
    val statSkinsOwned: String,
    val shopTitle: String,
    val shopCoinsLine: String,
    val owned: String,
    val coinsPriceSuffix: String,
    val buy: String,
    val equipped: String,
    val equip: String,
    val gameHudTime: String,
    val gameHudDeaths: String,
    val gameTimeLimitPrefix: String,
    val gameTimeLimitMiddle: String,
    val gameCoinsRun: String,
    val pause: String,
    val levelsButton: String,
    val doorLockedHint: String,
    val moveLeft: String,
    val moveRight: String,
    val jump: String,
    val timeUpTitle: String,
    val timeUpBody: String,
    val timeUpBodyNoLimit: String,
    val retry: String,
    val toList: String,
    val pauseTitle: String,
    val pauseHint: String,
    val resume: String,
    val toMainMenu: String,
    val levelCompleteTa: String,
    val levelComplete: String,
    val next: String,
    val toTimeAttackMode: String,
    val nextLevel: String,
    val toMenu: String,
    val replay: String,
    val gameCompleteTitle: String,
    val playAgain: String,
    val mainMenu: String,
    val resultDataUnavailable: String,
    val resultRun: String,
    val resultDeaths: String,
    val resultStars: String,
    val resultBest: String,
    val resultCoinsLine: String,
    val newRecordSuffix: String,
    val secondsShort: String,
    val timeHoursShort: String,
    val timeMinutesShort: String,
    val timeSecondsShort: String,
)

private val ruStrings = GameStrings(
    mainTitle = "Мини-платформер",
    mainSubtitle = "Платформер с уровнями и чекпоинтами",
    coinsLabel = "Монеты: ",
    play = "Играть",
    shop = "Магазин",
    achievements = "Достижения",
    records = "Рекорды",
    statistics = "Статистика",
    back = "Назад",
    levelSelectTitle = "Выбор уровня",
    levelSelectHint = "Нажмите номер уровня",
    timeAttackChip = "⚡ НА ВРЕМЯ",
    levelWord = "Уровень ",
    backToMainMenu = "Назад в главное меню",
    timeAttackScreenTitle = "На время",
    timeAttackScreenSubtitle = "У каждого уровня свой лимит (см. метку на кнопке). Отдельные трассы, не как в кампании.",
    backToLevelSelect = "Назад к выбору уровней",
    timeLimitNone = "⏱ —",
    recordsTitle = "Рекорды",
    recordsSortHint = "Сортировка: звезды ↓, время ↑",
    place1 = "1 место",
    place2 = "2 место",
    place3 = "3 место",
    placeSuffix = " место",
    medalGold = "[ЗОЛОТО]",
    medalSilver = "[СЕРЕБРО]",
    medalBronze = "[БРОНЗА]",
    achievementsTitle = "Достижения",
    achievementsUnlockedPrefix = "Открыто: ",
    achievementsAutoSave = "Прогресс сохраняется автоматически",
    achievementDone = "Готово",
    achievementLocked = "Закрыто",
    statisticsTitle = "Статистика",
    statisticsSubtitle = "Сводка по сохранению",
    statWalletCoins = "Монеты на счёте",
    statLifetimeDeaths = "Смертей всего",
    statLifetimeCoins = "Монет подобрано (всего)",
    statLevelsCompleted = "Прохождений уровней (всего)",
    statPlayTime = "Время в игре",
    statUnlockedLevels = "Открыто уровней кампании",
    statAchievements = "Достижения",
    statPaidSkins = "Платных скинов куплено",
    statSkinsOwned = "Скинов в коллекции",
    shopTitle = "Магазин скинов",
    shopCoinsLine = "Монеты: ",
    owned = "Куплено",
    coinsPriceSuffix = " монет",
    buy = "Купить",
    equipped = "Надето",
    equip = "Надеть",
    gameHudTime = "  Время: ",
    gameHudDeaths = "  Смерти: ",
    gameTimeLimitPrefix = "⏱ Лимит: ",
    gameTimeLimitMiddle = " с  ·  осталось ",
    gameCoinsRun = "Монеты: ",
    pause = "Пауза",
    levelsButton = "Уровни",
    doorLockedHint = "Дверь закрыта — нужен ключ",
    moveLeft = "Влево",
    moveRight = "Вправо",
    jump = "Прыжок",
    timeUpTitle = "Время вышло",
    timeUpBody = "Лимит %d с истёк — попробуй ещё раз.",
    timeUpBodyNoLimit = "Попробуй ещё раз.",
    retry = "Заново",
    toList = "К списку",
    pauseTitle = "Пауза",
    pauseHint = "Игра остановлена. Клавиша Esc — продолжить.",
    resume = "Продолжить",
    toMainMenu = "В главное меню",
    levelCompleteTa = "Уровень на время %d пройден!",
    levelComplete = "Уровень %d пройден!",
    next = "Следующий",
    toTimeAttackMode = "К режиму «на время»",
    nextLevel = "Следующий уровень",
    toMenu = "В меню",
    replay = "Переиграть",
    gameCompleteTitle = "Все уровни пройдены!",
    playAgain = "Играть снова",
    mainMenu = "Главное меню",
    resultDataUnavailable = "Данные уровня недоступны.",
    resultRun = "Забег: ",
    resultDeaths = " | Смерти: ",
    resultStars = " | Звезды: ",
    resultBest = "\nЛучшее: ",
    resultCoinsLine = "\nМонеты: ",
    newRecordSuffix = "  НОВОЕ!",
    secondsShort = " с",
    timeHoursShort = " ч ",
    timeMinutesShort = " мин ",
    timeSecondsShort = " с"
)

private val enStrings = GameStrings(
    mainTitle = "Mini platformer",
    mainSubtitle = "Levels, checkpoints, and challenges",
    coinsLabel = "Coins: ",
    play = "Play",
    shop = "Shop",
    achievements = "Achievements",
    records = "Records",
    statistics = "Statistics",
    back = "Back",
    levelSelectTitle = "Level select",
    levelSelectHint = "Tap a level number",
    timeAttackChip = "⚡ TIME ATTACK",
    levelWord = "Level ",
    backToMainMenu = "Back to main menu",
    timeAttackScreenTitle = "Time attack",
    timeAttackScreenSubtitle = "Each level has its own limit (see the button). Separate tracks from the campaign.",
    backToLevelSelect = "Back to level select",
    timeLimitNone = "⏱ —",
    recordsTitle = "Records",
    recordsSortHint = "Sort: stars ↓, time ↑",
    place1 = "1st place",
    place2 = "2nd place",
    place3 = "3rd place",
    placeSuffix = "th place",
    medalGold = "[GOLD]",
    medalSilver = "[SILVER]",
    medalBronze = "[BRONZE]",
    achievementsTitle = "Achievements",
    achievementsUnlockedPrefix = "Unlocked: ",
    achievementsAutoSave = "Progress is saved automatically",
    achievementDone = "Done",
    achievementLocked = "Locked",
    statisticsTitle = "Statistics",
    statisticsSubtitle = "Save summary",
    statWalletCoins = "Coins in wallet",
    statLifetimeDeaths = "Total deaths",
    statLifetimeCoins = "Coins collected (total)",
    statLevelsCompleted = "Level clears (total)",
    statPlayTime = "Play time",
    statUnlockedLevels = "Campaign levels unlocked",
    statAchievements = "Achievements",
    statPaidSkins = "Paid skins bought",
    statSkinsOwned = "Skins in collection",
    shopTitle = "Skin shop",
    shopCoinsLine = "Coins: ",
    owned = "Owned",
    coinsPriceSuffix = " coins",
    buy = "Buy",
    equipped = "Equipped",
    equip = "Equip",
    gameHudTime = "  Time: ",
    gameHudDeaths = "  Deaths: ",
    gameTimeLimitPrefix = "⏱ Limit: ",
    gameTimeLimitMiddle = "s  ·  left ",
    gameCoinsRun = "Coins: ",
    pause = "Pause",
    levelsButton = "Levels",
    doorLockedHint = "Door is locked — find the key",
    moveLeft = "Left",
    moveRight = "Right",
    jump = "Jump",
    timeUpTitle = "Time's up",
    timeUpBody = "The %ds limit expired — try again.",
    timeUpBodyNoLimit = "Try again.",
    retry = "Retry",
    toList = "To list",
    pauseTitle = "Paused",
    pauseHint = "Game paused. Esc — resume.",
    resume = "Resume",
    toMainMenu = "Main menu",
    levelCompleteTa = "Time attack level %d cleared!",
    levelComplete = "Level %d cleared!",
    next = "Next",
    toTimeAttackMode = "To time attack",
    nextLevel = "Next level",
    toMenu = "To menu",
    replay = "Replay",
    gameCompleteTitle = "All levels cleared!",
    playAgain = "Play again",
    mainMenu = "Main menu",
    resultDataUnavailable = "Level data unavailable.",
    resultRun = "Run: ",
    resultDeaths = " | Deaths: ",
    resultStars = " | Stars: ",
    resultBest = "\nBest: ",
    resultCoinsLine = "\nCoins: ",
    newRecordSuffix = "  NEW!",
    secondsShort = " s",
    timeHoursShort = " h ",
    timeMinutesShort = " min ",
    timeSecondsShort = " s"
)

fun gameStrings(lang: AppLanguage): GameStrings =
    when (lang) {
        AppLanguage.English -> enStrings
        AppLanguage.Russian -> ruStrings
    }

fun skinLocalizedName(skin: PlayerSkinOption, lang: AppLanguage): String =
    when (lang) {
        AppLanguage.Russian -> skin.nameRu
        AppLanguage.English -> skin.nameEn
    }

fun formatPlayTimeMs(ms: Long, lang: AppLanguage): String {
    val totalSec = (ms / 1000L).coerceAtLeast(0L)
    val h = totalSec / 3600L
    val m = (totalSec % 3600L) / 60L
    val sec = totalSec % 60L
    return when (lang) {
        AppLanguage.Russian -> when {
            h > 0L -> "$h ч $m мин"
            m > 0L -> "$m мин $sec с"
            else -> "$sec с"
        }
        AppLanguage.English -> when {
            h > 0L -> "${h}h ${m}m ${sec}s"
            m > 0L -> "${m}m ${sec}s"
            else -> "${sec}s"
        }
    }
}

fun formatCentisecondsLocalized(totalCentiseconds: Int, secondsShort: String): String {
    val safe = totalCentiseconds.coerceAtLeast(0)
    val secondsPart = safe / 100
    val centisecondsPart = safe % 100
    return "$secondsPart.${centisecondsPart.toString().padStart(2, '0')}$secondsShort"
}
